version: "3.8"

services:
  hiltolp-site:
    image: node:18-alpine
    container_name: hiltolp-site
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run build && npm start"
